import test from 'node:test';
import assert from 'node:assert/strict';
import { extractCapabilitiesFromSqlDdl } from '../src/source-capability-frontends.mjs';

test('SQL DDL frontend canonically separates nested numeric types from column constraints', () => {
  const bundle = extractCapabilitiesFromSqlDdl(`
    CREATE TABLE accounts (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      email VARCHAR(255) NOT NULL UNIQUE,
      balance NUMERIC(12, 2) NOT NULL CHECK (balance >= 0),
      metadata JSONB DEFAULT '{}'::jsonb,
      CONSTRAINT account_email_check CHECK (email <> '')
    );
  `, { dialect: 'postgresql-18-subset' });

  const accounts = bundle.capabilities.find(spec => spec.id === 'sql_table_accounts');
  const diagnostic = JSON.stringify({
    inputs: accounts?.operation?.inputs ?? null,
    invariants: accounts?.semantics?.invariants ?? null,
    coverage: bundle.coverage,
  });

  assert.ok(accounts, diagnostic);
  assert.ok(accounts.operation.inputs.includes('balance_numeric_12_2'), diagnostic);
  assert.ok(accounts.semantics.invariants.includes('column balance type NUMERIC(12, 2)'), diagnostic);
  assert.ok(accounts.semantics.invariants.includes('column balance not null'), diagnostic);
  assert.ok(accounts.semantics.invariants.includes('column balance check constraint'), diagnostic);
});
