import test from 'node:test';
import assert from 'node:assert/strict';
import {
  RCL_SOURCE_CAPABILITY_BUNDLE_FORMAT,
  RCLSourceCapabilityFrontendError,
  detectSourceCapabilityKind,
  extractCapabilitiesFromJsonSchema,
  extractCapabilitiesFromOpenApi,
  extractCapabilitiesFromSqlDdl,
  extractSourceCapabilities,
  metabolizeSourceCapabilityBundle,
} from '../src/source-capability-frontends.mjs';

const jsonSchema = {
  $schema: 'https://json-schema.org/draft/2020-12/schema',
  $id: 'https://example.test/schemas/order',
  title: 'Order',
  type: 'object',
  required: ['id', 'total'],
  additionalProperties: false,
  properties: {
    id: { type: 'string', minLength: 1 },
    total: { type: 'number', minimum: 0 },
  },
  $defs: {
    Address: {
      type: 'object',
      required: ['city'],
      properties: { city: { type: 'string' } },
    },
  },
};

const openApi = {
  openapi: '3.1.2',
  info: { title: 'Order API', version: '1.0.0' },
  servers: [{ url: 'https://api.example.test' }],
  paths: {
    '/orders/{id}': {
      parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
      get: {
        operationId: 'getOrder',
        responses: {
          200: {
            description: 'ok',
            content: { 'application/json': { schema: { $ref: '#/components/schemas/Order' } } },
          },
          404: { description: 'missing' },
        },
      },
    },
    '/orders': {
      post: {
        operationId: 'createOrder',
        requestBody: {
          required: true,
          content: { 'application/json': { schema: { $ref: '#/components/schemas/Order' } } },
        },
        responses: { 201: { description: 'created' } },
      },
    },
  },
  components: {
    schemas: {
      Order: { type: 'object', required: ['id'], properties: { id: { type: 'string' } } },
    },
  },
};

const sql = `
-- relational source
CREATE TABLE accounts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  balance NUMERIC(12, 2) NOT NULL CHECK (balance >= 0),
  metadata JSONB DEFAULT '{}'::jsonb,
  CONSTRAINT account_email_check CHECK (email <> '')
);

CREATE TABLE transfers (
  id BIGINT PRIMARY KEY,
  from_account BIGINT NOT NULL REFERENCES accounts(id),
  to_account BIGINT NOT NULL REFERENCES accounts(id),
  amount NUMERIC(12,2) NOT NULL,
  UNIQUE (from_account, to_account, id)
);
`;

test('detects supported source capability kinds', () => {
  assert.equal(detectSourceCapabilityKind(jsonSchema), 'json-schema');
  assert.equal(detectSourceCapabilityKind(openApi), 'openapi');
  assert.equal(detectSourceCapabilityKind(sql), 'sql-ddl');
});

test('extracts root and $defs JSON Schema capabilities with structural invariants', () => {
  const bundle = extractCapabilitiesFromJsonSchema(jsonSchema);
  assert.equal(bundle.format, RCL_SOURCE_CAPABILITY_BUNDLE_FORMAT);
  assert.equal(bundle.frontend, 'json-schema');
  assert.equal(bundle.capabilityCount, 2);
  assert.equal(bundle.capabilities[0].id, 'json_schema_order');
  assert.equal(bundle.capabilities[0].lowering.providerRequired, false);
  assert.ok(bundle.capabilities[0].semantics.invariants.includes('$ required id,total'));
  assert.ok(bundle.capabilities[0].semantics.invariants.includes('$ additionalProperties false'));
  assert.ok(bundle.capabilities[1].evidence.provenance.includes('$defs/Address'));
});

test('extracts one OpenAPI capability per operation and distinguishes reads from mutations', () => {
  const bundle = extractCapabilitiesFromOpenApi(openApi);
  assert.equal(bundle.capabilityCount, 2);
  const read = bundle.capabilities.find(spec => spec.operation.name === 'getorder');
  const mutation = bundle.capabilities.find(spec => spec.operation.name === 'createorder');
  assert.ok(read);
  assert.ok(mutation);
  assert.equal(read.semantics.effects[0].name, 'ExternalRead');
  assert.equal(mutation.semantics.effects[0].name, 'ExternalMutation');
  assert.equal(mutation.lowering.providerRequired, true);
  assert.ok(read.semantics.invariants.includes('required path parameter id:string'));
  assert.ok(mutation.semantics.invariants.includes('request body required'));
});

test('extracts multiple CREATE TABLE capabilities without splitting nested type commas', () => {
  const bundle = extractCapabilitiesFromSqlDdl(sql, { dialect: 'postgresql-18-subset' });
  assert.equal(bundle.capabilityCount, 2);
  assert.equal(bundle.coverage.columnCount, 8);
  const accounts = bundle.capabilities.find(spec => spec.id === 'sql_table_accounts');
  assert.ok(accounts);
  assert.ok(accounts.operation.inputs.includes('balance_numeric_12_2'));
  assert.ok(accounts.semantics.invariants.includes('column balance not null'));
  assert.ok(accounts.semantics.invariants.some(value => value.includes('account_email_check')));
  assert.equal(accounts.lowering.provider, 'sql:postgresql_18_subset');
});

test('generic extraction is deterministic across JSON object key order', () => {
  const first = extractSourceCapabilities(jsonSchema);
  const reordered = {
    properties: jsonSchema.properties,
    additionalProperties: false,
    required: ['id', 'total'],
    type: 'object',
    title: 'Order',
    $id: jsonSchema.$id,
    $defs: jsonSchema.$defs,
    $schema: jsonSchema.$schema,
  };
  const second = extractSourceCapabilities(reordered);
  assert.equal(first.sourceRoot, second.sourceRoot);
  assert.deepEqual(first.capabilityRoots, second.capabilityRoots);
  assert.equal(first.root, second.root);
});

test('records unsupported OpenAPI remote references instead of claiming resolution', () => {
  const bundle = extractCapabilitiesFromOpenApi({
    ...openApi,
    paths: {
      '/remote': {
        get: {
          responses: {
            200: {
              description: 'remote',
              content: { 'application/json': { schema: { $ref: 'https://example.test/schema.json' } } },
            },
          },
        },
      },
    },
  });
  assert.ok(bundle.diagnostics.some(item => item.code === 'RCL_SOURCE_OPENAPI_REMOTE_REF'));
  assert.equal(bundle.coverage.remoteReferenceResolution, false);
});

test('rejects undetected and unsupported source inputs', () => {
  assert.throws(
    () => extractSourceCapabilities('not a supported source'),
    error => error instanceof RCLSourceCapabilityFrontendError
      && error.code === 'RCL_SOURCE_FRONTEND_UNDETECTED',
  );
  assert.throws(
    () => extractCapabilitiesFromOpenApi({ swagger: '2.0', paths: {} }),
    error => error instanceof RCLSourceCapabilityFrontendError
      && error.code === 'RCL_SOURCE_OPENAPI_VERSION',
  );
});

test('preserves OpenAPI component reference names in generated contracts', () => {
  const bundle = extractCapabilitiesFromOpenApi(openApi);
  const read = bundle.capabilities.find(spec => spec.operation.name === 'getorder');
  assert.ok(read.operation.outputs.some(value => value.includes('order')));
});

test('metabolizes an extracted bundle through an injectable evidence-preserving batch adapter', () => {
  const bundle = extractCapabilitiesFromJsonSchema(jsonSchema, { includeDefinitions: false });
  const batch = metabolizeSourceCapabilityBundle(bundle, {
    metabolize(spec) {
      const body = {
        format: 'rcl.capability-metabolism-report.v0.1',
        capability: spec.id,
        assessment: { stage: 'semantic-absorbed' },
        specRoot: spec.root,
      };
      return Object.freeze({ ...body, root: `report:${spec.root}` });
    },
  });
  assert.equal(batch.capabilityCount, 1);
  assert.equal(batch.stageCounts['semantic-absorbed'], 1);
  assert.equal(batch.reportRoots[0], `report:${bundle.capabilities[0].root}`);
});

test('parses schema-qualified quoted SQL table identifiers', () => {
  const bundle = extractCapabilitiesFromSqlDdl('CREATE TABLE "public"."events" (id BIGINT PRIMARY KEY);');
  assert.equal(bundle.capabilities[0].id, 'sql_table_public_events');
  assert.ok(bundle.capabilities[0].semantics.invariants.includes('relational table public.events'));
});
